name: 🛠 Template Validate

on:
  pull_request:
    paths:
      - '**.yaml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with: 
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.x

      - name: w3discovery install
        run: go install -v github.com/w3security/w3discovery/v2/cmd/w3discovery@latest

      - name: Template Validation
        run: |
          cp -r ${{ github.workspace }} $HOME
          w3discovery -duc -validate
          w3discovery -duc -validate -w ./workflows
